theme: jekyll-theme-minimal
url: "https://beijingbitcoinmeetup.github.io/EO" 
title: Entrepreneurs Organisation - Beijing Bitcoin Meetup
logo: "https://beijingbitcoinmeetup.github.io/EO/assets/bbm.png"
